language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
    secure: rSvLc5hUankIExFX2/F02oxfHfn/NJOffgIt6edzFM/KAlRSn86UIxL6Slc3Tnz/lbhWb40v9zHTvtwzO/gdjaJ/6i0Zqf3rK2EpBF2aNRudRrD6tkEnTLUekquF0KmFGeTmDaDlkysrtoqP6t7iRr3kXrwIRBvN8ANFISMvjJ4INFAhna86toEkyDOBMyOW7QSGvFlhOSNLyK2v1KTcy0OoFKbou7W3sQpa8C2upq3qW5vGHou7xUMyLrXjJ00xzBkOk8lt4a2uOjn7JdWLdi7u3NImF2boxPoIFvMFRMpYlcAog0toSwagJOgvaXcbn7GxSAgrDosUXQWAJtlXrSjY//XGVinGgwBIJdp82JbquX9PnCtmtFwnCfP6aoZ3NCYkF36HX2+0Od1hnIbGX6KBcHYGcfZdUBEXnVUJgAwYgAdadIjP9pX94XuRzTg/3bhzHgkETTNXwv57QAdbd6EWtKSTCNI5CZkgStpVXDcCECReft6LFiDHoyiNUEiKdVhlMuRvRytJs+F7fdT03j5oQY8QeieEUYb43RlxeSslAabwizC5WDiupQwf3gNhPz6ygDmEIV1DVFHvxpnbHAVPf+Wh87BzuReJG1bAqt5zSpiO1tueTwz8mf2qPy3yw5B/Ohk69YzZ/tfHaiesy/cqdkc2e0SAZRCeeet/Fxw=
